#!/bin/bash
set -ex

# orbfit directory
mkdir orbfit
cd orbfit

# download Orbfit
wget http://adams.dm.unipi.it/orbfit/OrbFit5.0.7.tar.gz
tar xvzf OrbFit5.0.7.tar.gz

# dependencies
./config -O gfortran

make

mkdir -p ~/bin
cp src/fitobs/fitobs.x ~/bin

# now build the ephemerides
cd lib
wget https://epyc.astro.washington.edu/~maria8ch/jpleph
wget https://epyc.astro.washington.edu/~maria8ch/AST17.bai
wget https://epyc.astro.washington.edu/~maria8ch/AST17.bep

#cd src/jpleph

#for fn in header.431_572 ascp00000.431 ascp01000.431 ascp02000.431 ascp03000.431; do
#    wget "epyc.astro.washington.edu/~maria8ch/$fn"
#done

#PATH=".:$PATH" make ephemerides
#cd ../../lib/
#ln -s ../src/jpleph/jpleph

