#!/bin/bash
set -ex

# build orbfit
mkdir orbfit
cd orbfit

wget http://adams.dm.unipi.it/orbfit/OrbFit5.0.7.tar.gz
tar xvzf OrbFit5.0.7.tar.gz

./config -O gfortran

make

mkdir -p ~/bin
cp src/fitobs/fitobs.x ~/bin

# now build the ephemerides
cd src/jpleph

for fn in header.431_572 ascp00000.431 ascp01000.431 ascp02000.431 ascp03000.431; do
    wget "ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de431/$fn"
done

PATH=".:$PATH" make ephemerides
cd ../../lib/
ln -s ../src/jpleph/jpleph

